spring:
  application:
    name: store
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #1min
    refreshTokenExpiration: 86400 #2min
    absoluteSessionInSeconds: 172800 #3minutes #for demo purpose
  profiles:
    active: dev

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}